version: "3.7"
services: 
    minecraft: 
        image: jonasbonno/ftb-infinity:3.1.0
        container_name: minecraft
        ports: 
            - 25565:25565
        volumes: 
            - /root/minecraft-data:/minecraft/world